### ISSUE TITLE
docker-bundle - Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

### ISSUE THREAD

**Issue by spacedebris** [drgomesp/symfony-docker#33]
Hi, after cloning repo, made composer install and passing by the parameters I got following error.
```
[RuntimeException]                                                                                                                                                             
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                                                                                      
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DockerBundle" from namespace "Drgomesp\DockerBundle".            
  Did you forget a "use" statement for another namespace? in /var/www/html/docker/01-symfony-docker/app/AppKernel.php:19                                                         
  Stack trace:      

  #0 /var/www/html/docker/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(396): AppKernel->registerBundles()                                
  #1 /var/www/html/docker/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()    
  #2 /var/www/html/docker/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(68): Symfony\Component\HttpKernel\Kernel->boot()   
  #3 /var/www/html/docker/01-symfony-docker/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(117): Symfony\Bundle\FrameworkBundle\Console\Application->doRu  
  n(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Consol in /var/www/html/docker/01-symfony-docker/app/AppKernel.php on line 19   
```

command : `composer require drgomesp/docker-bundle` gives 
`
```
Installation failed, reverting ./composer.json to its original content.

                                                                                                                          
  [Composer\DependencyResolver\SolverProblemsException]                                                                   
    Problem 1                                                                                                             
      - Installation request for drgomesp/docker-bundle dev-master -> satisfiable by drgomesp/docker-bundle[dev-master].  
      - drgomesp/docker-bundle dev-master requires symfony/yaml ^3.1 -> no matching package found.                        
  Potential causes:                                                                                                       
   - A typo in the package name                                                                                           
   - The package is not available in a stable-enough version according to your minimum-stability setting                  
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.                                   
  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.  
```
`
Thank you in advance for your help...

**Comment by enricocarraro** [comment]
I'm having the same problem

**Comment by overbe** [comment]
To fix this error you need:
In 

`../app/AppKernel.php:19
`

change 

`            new Drgomesp\DockerBundle\DockerBundle(),
`
to

`            new Drgomesp\DockerBundle\SymfonyDockerBundle(),
`

**Comment by drgomesp** [comment]
Hey guys. I've reestructured this project a little bit, and now you don't require docker-bundle anymore. Just pull from this repo and run `docker-compose up` from main folder.
